---
- block:
  - name: Set hostname on Linux systems
    hostname:
      name: "{{ hostname_new_name }}"
    when: ansible_os_family != "Windows"
  become: true

# There's no hostname module for Windows, but there is a Powershell cmdlet!
# The failed_when: condition exists because it raises a stink when the hostname already matches the new one.
# The win_shell: module is necessary because win_command can't "see the file".
- name: Set hostname on Windows systems
  win_shell: "Rename-Computer -NewName {{ hostname_new_name }}"
  when: ansible_os_family == "Windows"
  register: set_hostname_windows_change_result
  changed_when: "set_hostname_windows_change_result.rc == 0"
  failed_when: "'the new name is the same as the current' not in set_hostname_windows_change_result.stderr"
  notify: "Windows reboot for name change"

- name: Reboot Windows to apply new hostname
  win_reboot:
  when: ansible_os_family == "Windows"

- name: Add new hostname to Ansible's facts
  setup:
